# syntax=docker/dockerfile:1-labs
#
# Unified Build Tool
# Copyright (C) 2021-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Using Ubuntu as base, since it includes the Debian keyring packages:
ARG BASE="ubuntu:latest"
FROM --platform=${BUILDPLATFORM} ${BASE}

COPY pbuilderrc /etc
RUN <<EOF
   apt update -qq
   apt dist-upgrade -y -qq
   env DEBIAN_FRONTEND=noninteractive apt install -qq -y --no-install-recommends \
      bash-completion \
      debian-archive-keyring \
      debian-ports-archive-keyring \
      eatmydata \
      fakeroot \
      iproute2 \
      joe \
      less \
      pbuilder \
      pigz \
      qemu-user-static
   apt clean
EOF
