.\" build-tool
.\" ==========================================================================
.\"              ____        _ _     _     _____           _
.\"             | __ ) _   _(_) | __| |   |_   _|__   ___ | |___
.\"             |  _ \| | | | | |/ _` |_____| |/ _ \ / _ \| / __|
.\"             | |_) | |_| | | | (_| |_____| | (_) | (_) | \__ \
.\"             |____/ \__,_|_|_|\__,_|     |_|\___/ \___/|_|___/
.\"                           --- Build-Tools ---
.\"                https://www.nntb.no/~dreibh/system-tools/
.\" ==========================================================================
.\"
.\" Unified Build Tool
.\" Copyright (C) 2021-2026 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd November 27, 2025
.Dt build-tool 1
.Os build-tool
.\" ###### Name #############################################################
.Sh NAME
.Nm build-tool
.Nd Build Tool
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.\" -------------------------------------------------------
.Nm build-tool info
.\" -------------------------------------------------------
.Nm build-tool make-source-tarball
.Op Fl Fl skip-signing
.\" -------------------------------------------------------
.Nm build-tool build-deb
.Op Fl Fl summary=file
codename ...
.Op Fl Fl skip-signing
.Op Fl Fl architecture=arch[,...]
.\" -------------------------------------------------------
.Nm build-tool fetch-debian-changelog
codename
.\" -------------------------------------------------------
.Nm build-tool make-source-rpm
.Op Fl Fl summary=file
.Op Fl Fl summary=file
release ...
.Op Fl Fl skip-signing
.\" -------------------------------------------------------
.Nm build-tool build-rpm
.Op Fl Fl summary=file
release ...
.Op Fl Fl skip-signing
.Op Fl Fl architecture=arch[,...]
.\" ###### Description ######################################################
.Sh DESCRIPTION
Build Tool is a tool to help creating and maintaining package
builds for Debian/Ubuntu, Fedora, FreeBSD and other systems.
It performs the following tasks:
.Bl -tag -width indent
.It creating a source tarball,
.It creating a source package (Debian/Ubuntu, Fedora, etc.),
.It building binary packages from the source package (including
cross-architecture builds).
.El
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It Fl h | Fl Fl help
Prints command-line parameters.
.It ...
FIXME! TBD
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It build-tool
.El
