#!/usr/bin/env bash
# ==========================================================================
#              ____        _ _     _     _____           _
#             | __ ) _   _(_) | __| |   |_   _|__   ___ | |___
#             |  _ \| | | | | |/ _` |_____| |/ _ \ / _ \| / __|
#             | |_) | |_| | | | (_| |_____| | (_) | (_) | \__ \
#             |____/ \__,_|_|_|\__,_|     |_|\___/ \___/|_|___/
#
#                           --- Build-Tools ---
#                https://www.nntb.no/~dreibh/system-tools/
# ==========================================================================
#
# NorNet Core PBuilder Helper Script
# Copyright (C) 2012-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -eu


CLEANUP="
   /var/cache/pbuilder/aptcache
   /var/cache/pbuilder/*/aptcache
   /var/cache/pbuilder/result
   /var/cache/pbuilder/*/result
   /var/cache/pbuilder/*.tgz
   /var/cache/pbuilder/*.tmp
   /var/cache/pbuilder/build
"

for directory in ${CLEANUP} ; do
   if [ -e "${directory}" ] ; then
      echo "Cleaning up ${directory} ..."
      find "${directory}" -type f -print0 | xargs -0 -r rm -f
   fi
done

du -sch /var/cache/pbuilder

echo "Running fstrim ..."
fstrim -v /var/cache/pbuilder
