#!/usr/bin/env bash

while [ $# -gt 0 ] ; do
   echo >&2 "====== $1 ======"
   grep "^\.Op Fl" "$1" |      \
      sed -e "s/Fl /-/g"       \
          -e "s/^\.Op //"      \
          -e 's/ [\|] /\n/g' | \
         sed -e 's/ .*$//'     \
             -e '/^[ ]*$/d'
   shift
done
