#!/usr/bin/env bash
# ==========================================================================
#              ____        _ _     _     _____           _
#             | __ ) _   _(_) | __| |   |_   _|__   ___ | |___
#             |  _ \| | | | | |/ _` |_____| |/ _ \ / _ \| / __|
#             | |_) | |_| | | | (_| |_____| | (_) | (_) | \__ \
#             |____/ \__,_|_|_|\__,_|     |_|\___/ \___/|_|___/
#
#                           --- Build-Tools ---
#                https://www.nntb.no/~dreibh/system-tools/
# ==========================================================================
#
# Packaging Scripts
# Copyright (C) 2025-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail


APKBUILD="packaging/APKBUILD"

# ====== Get port default ===================================================
PKGNAME="$(grep "^pkgname=" "${APKBUILD}" | cut -d= -f2)"
PKGVER="$(grep "^pkgver=" "${APKBUILD}" | cut -d= -f2)"
TARBALL="${PKGNAME}-${PKGVER}.tar.xz"
echo "Processing ${PKGNAME} ..."

# ====== Update =============================================================
if [ ! -f "${TARBALL}" ] ; then
   echo >&2 "ERROR: Cannot find source tarball ${TARBALL}.tar.xz!"
   exit 1
fi
SHA512SUM="$(sha512sum "${TARBALL}")"

(
cat <<EOF
sha512sums="
${SHA512SUM}
"
EOF
) | text-block \
   --input "${APKBUILD}" --in-place \
   --begin-tag 'sha512sums="' --end-tag '"' --full-tag-lines --include-tags \
   --replace - \
   --min-actions 1 --max-actions 1
