#!/usr/bin/env bash

set -eu

today="$(LC_ALL=C.UTF-8 date +"%B %d, %Y" | sed -e "s/ 0/ /")"
# echo "${today}"

while [ $# -gt 0 ] ; do
   echo >&2 "Updating $1 ..."
   sed -e "s/^\.Dd [A-Z].*$/.Dd ${today}/" -i "$1"
   shift
done
